# update && upgrade ubuntu 
- name: upgrade Ubuntu 
  apt: 
    name: "*"
    update_cache: yes 
    cache_valid_time: 86400 
    state: latest 
    force_apt_get: true 
    autoclean: yes 
    autoremove: yes 